### ISSUE TITLE
Broken nesting

### ISSUE THREAD

**Issue by smth** [static-dev/spike#88]
This is probably going to need to be resolved elsewhere eventually, but thought I'd start here, to see if anyone can replicate this issue. I'm finding that nesting beyond one level is not getting formatted, and being outputted verbatim. There is a quirk here in that this issue does not apply the first nested sibling.

**To replicate**
1. Create a new "sugarfree" Spike project
2. Use the below CSS
```css
main {
  & p {
    color: red;

    & strong {
      color: orange;
    }
  }

  & ul {
    background-color: black;

    & li {
      color: green;
    }
  }
}
```
What I'm getting as a result:
```css
main ul {
    background-color: black;

    & li {
      color: green;
    }
}main {
}

main p {
    color: red;
}

main p strong {
      color: orange;
}
```
The `li` has not been properly parsed, and the whole `ul` section is returned out of order.

---

**Versions that I'm using** (as specified by [the template](https://github.com/static-dev/spike-tpl-sugarfree))
Note: the [sugarfree template](https://github.com/static-dev/spike-tpl-sugarfree) specifies older dependencies than the base template (intentional?)

- Spike CSS Standards v1.1.0 
- Spike v1.3.1
